# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'ExNihilo.sln'
      PROJECT: 'ExNihilo/ExNihilo.csproj'
      TESTS: 'Tests/Tests.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    - name: Restore dependencies project
      run: dotnet restore $SOLUTION/$PROJECT
    - name: Restore dependencies tests
      run: dotnet restore $SOLUTION/$TESTS

    - name: Build project
      run: dotnet build $SOLUTION/$PROJECT --configuration $BUILD_CONFIG --no-restore
    - name: Build tests
      run: dotnet build $SOLUTION/$TESTS --configuration $BUILD_CONFIG --no-restore
      
    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
