# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Nuget

on:
  push:
    branches: [ "release" ]
  pull_request:
    types: [ closed ]
    branches: [ "release" ]

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      PROJECT: './ExNihilo/ExNihilo.csproj'
      TESTS: './Tests/Tests.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    - name: Restore dependencies project
      run: dotnet restore $PROJECT
    - name: Restore dependencies tests
      run: dotnet restore $TESTS

    - name: Build tests
      run: dotnet build $TESTS --configuration $BUILD_CONFIG --no-restore
    - name: Run tests
      run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

    - name: Pack project
      run: dotnet pack $PROJECT --configuration $BUILD_CONFIG --no-restore

    - name: Push generated package to Nuget registry
      run: dotnet nuget push **\*.nupkg --skip-duplicate -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
