name: Publish NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      BUILD_CONFIG: Release
      PROJECT: ./ExNihilo/ExNihilo.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Write release version
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "Version: $VERSION"

      - name: Restore dependencies
        run: dotnet restore $PROJECT

      - name: Pack project
        run: dotnet pack $PROJECT --configuration $BUILD_CONFIG --no-restore -p:PackageVersion=$VERSION -o ./out

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
            ./out/*.nupkg \
            --generate-notes \
            --title "$GITHUB_REF_NAME"

      - name: Push package to NuGet
        run: dotnet nuget push "./out/*.nupkg" --skip-duplicate --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.NUGET_API_KEY }}"